FROM outstand/ruby-base:2.3.1-alpine
MAINTAINER Ryan Schlesinger <ryan@outstand.com>

RUN addgroup heartbeat && \
    adduser -S -G heartbeat heartbeat

ENV NODE_HEARTBEAT_VERSION=0.1.1

RUN apk --no-cache add --virtual build-dependencies build-base && \
    gem install node_heartbeat -v ${NODE_HEARTBEAT_VERSION} && \
    apk del build-dependencies

COPY scripts/docker-entrypoint.sh /docker-entrypoint.sh

ENV DUMB_INIT_SETSID 0
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["help"]
